2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Configure stats pid to 3852806
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Loading settings from /home/hawk/.config/wandb/settings
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Loading settings from /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/settings
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-04-09 12:47:08,175 INFO    MainThread:3852806 [wandb_init.py:_log_setup():520] Logging user logs to /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_124708-25wuae3q/logs/debug.log
2025-04-09 12:47:08,176 INFO    MainThread:3852806 [wandb_init.py:_log_setup():521] Logging internal logs to /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_124708-25wuae3q/logs/debug-internal.log
2025-04-09 12:47:08,176 INFO    MainThread:3852806 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x76024c50cdf0>
2025-04-09 12:47:08,176 INFO    MainThread:3852806 [wandb_init.py:init():560] calling init triggers
2025-04-09 12:47:08,176 INFO    MainThread:3852806 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'SNR': 10, 'CNR': 15, 'max_lr': 0.001, 'beta_end': 0.02, 'final_lr': 1e-05, 'num_heads': 8, 'beta_start': 0.0001, 'num_layers': 6, 'batch_size': 16, 'num_epochs': 400, 'noise_steps': 2000, 'num_workers': 4, 'weight_decay': 0.0001, 'warmup_steps': 4000, 'dataset_size': 500, 'time_emb_dim': 256, 'learning_rate': 0.0001, 'scheduler_type': 'linear'}
2025-04-09 12:47:08,176 INFO    MainThread:3852806 [wandb_init.py:init():610] starting backend
2025-04-09 12:47:08,176 INFO    MainThread:3852806 [wandb_init.py:init():614] setting up manager
2025-04-09 12:47:08,180 INFO    MainThread:3852806 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-09 12:47:08,180 INFO    MainThread:3852806 [wandb_init.py:init():622] backend started and connected
2025-04-09 12:47:08,184 INFO    MainThread:3852806 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2025-04-09 12:47:08,184 INFO    MainThread:3852806 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-09 12:47:08,184 INFO    MainThread:3852806 [wandb_init.py:init():711] updated telemetry
2025-04-09 12:47:08,188 INFO    MainThread:3852806 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-04-09 12:47:08,855 INFO    MainThread:3852806 [wandb_run.py:_on_init():2402] communicating current version
2025-04-09 12:47:09,353 INFO    MainThread:3852806 [wandb_run.py:_on_init():2411] got version response upgrade_message: "wandb version 0.19.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-04-09 12:47:09,353 INFO    MainThread:3852806 [wandb_init.py:init():795] starting run threads in backend
2025-04-09 12:47:09,516 INFO    MainThread:3852806 [wandb_run.py:_console_start():2380] atexit reg
2025-04-09 12:47:09,516 INFO    MainThread:3852806 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-04-09 12:47:09,516 INFO    MainThread:3852806 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-04-09 12:47:09,516 INFO    MainThread:3852806 [wandb_run.py:_redirect():2325] Redirects installed.
2025-04-09 12:47:09,517 INFO    MainThread:3852806 [wandb_init.py:init():838] run started, returning control to user process
2025-04-09 12:47:09,517 INFO    MainThread:3852806 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2025-04-09 12:47:09,517 INFO    MainThread:3852806 [wandb_init.py:_pause_backend():431] pausing backend
2025-04-09 12:47:09,525 INFO    MainThread:3852806 [wandb_init.py:_resume_backend():436] resuming backend
2025-04-09 12:47:11,935 INFO    MainThread:3852806 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2025-04-09 12:47:11,935 INFO    MainThread:3852806 [wandb_init.py:_pause_backend():431] pausing backend
2025-04-09 12:47:11,943 INFO    MainThread:3852806 [wandb_init.py:_resume_backend():436] resuming backend
2025-04-09 12:47:11,943 INFO    MainThread:3852806 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2025-04-09 12:47:11,944 INFO    MainThread:3852806 [wandb_init.py:_pause_backend():431] pausing backend
2025-04-09 12:47:11,948 INFO    MainThread:3852806 [wandb_init.py:_resume_backend():436] resuming backend
2025-04-09 12:47:12,438 INFO    MainThread:3852806 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2025-04-09 12:47:12,438 INFO    MainThread:3852806 [wandb_init.py:_pause_backend():431] pausing backend
2025-04-09 12:47:12,445 INFO    MainThread:3852806 [wandb_init.py:_resume_backend():436] resuming backend
2025-04-09 12:47:12,529 INFO    MainThread:3852806 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2025-04-09 12:47:12,529 INFO    MainThread:3852806 [wandb_init.py:_pause_backend():431] pausing backend
