2025-04-17 15:08:21,374 INFO    MainThread:1148890 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-17 15:08:21,374 INFO    MainThread:1148890 [wandb_setup.py:_flush():67] Configure stats pid to 1148890
2025-04-17 15:08:21,374 INFO    MainThread:1148890 [wandb_setup.py:_flush():67] Loading settings from /home/hawk/.config/wandb/settings
2025-04-17 15:08:21,374 INFO    MainThread:1148890 [wandb_setup.py:_flush():67] Loading settings from /home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/wandb/settings
2025-04-17 15:08:21,374 INFO    MainThread:1148890 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-17 15:08:21,374 INFO    MainThread:1148890 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250417_150821-uvnset7t/logs/debug.log
2025-04-17 15:08:21,375 INFO    MainThread:1148890 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250417_150821-uvnset7t/logs/debug-internal.log
2025-04-17 15:08:21,375 INFO    MainThread:1148890 [wandb_init.py:monkeypatch_ipython():581] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7dd2bef3f800>
2025-04-17 15:08:21,375 INFO    MainThread:1148890 [wandb_init.py:init():781] calling init triggers
2025-04-17 15:08:21,375 INFO    MainThread:1148890 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'beta_end': 0.02, 'beta_start': 0.0001, 'batch_size': 16, 'num_epochs': 400, 'noise_steps': 2000, 'num_workers': 4, 'time_emb_dim': 256, 'learning_rate': 0.0001, 'scheduler_type': 'linear', '_wandb': {}}
2025-04-17 15:08:21,375 INFO    MainThread:1148890 [wandb_init.py:init():809] starting backend
2025-04-17 15:08:21,375 INFO    MainThread:1148890 [wandb_init.py:init():813] sending inform_init request
2025-04-17 15:08:21,379 INFO    MainThread:1148890 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-17 15:08:21,379 INFO    MainThread:1148890 [wandb_init.py:init():823] backend started and connected
2025-04-17 15:08:21,380 INFO    MainThread:1148890 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-04-17 15:08:21,381 INFO    MainThread:1148890 [wandb_init.py:init():915] updated telemetry
2025-04-17 15:08:21,385 INFO    MainThread:1148890 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-17 15:08:22,138 INFO    MainThread:1148890 [wandb_init.py:init():1014] starting run threads in backend
2025-04-17 15:08:22,164 INFO    MainThread:1148890 [wandb_run.py:_console_start():2454] atexit reg
2025-04-17 15:08:22,164 INFO    MainThread:1148890 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-17 15:08:22,164 INFO    MainThread:1148890 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-17 15:08:22,164 INFO    MainThread:1148890 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-17 15:08:22,165 INFO    MainThread:1148890 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-17 15:08:22,165 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 15:08:22,165 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 15:08:22,168 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 15:08:26,171 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 15:08:26,171 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 15:08:26,174 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 15:08:26,739 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 15:08:26,739 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 15:08:26,743 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:05:35,055 WARNING MsgRouterThr:1148890 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/hawk/Desktop/Heavy-Clutter-Detection/finalDiffusion/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-17 17:05:35,056 INFO    MsgRouterThr:1148890 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-17 17:05:35,260 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:05:35,260 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:05:41,011 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:05:43,570 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:05:43,570 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:05:47,292 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:05:49,841 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:05:49,841 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:06:00,791 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:06:03,261 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:06:03,261 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:06:05,997 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:06:08,489 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:06:08,489 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:06:13,974 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:06:16,431 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:06:16,431 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:06:19,881 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:06:22,356 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:06:22,356 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:06:30,642 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:06:33,132 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:06:33,132 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-17 17:06:36,801 INFO    MainThread:1148890 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-17 17:06:39,255 INFO    MainThread:1148890 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-17 17:06:39,255 INFO    MainThread:1148890 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
