2025-04-09 10:31:17,773 INFO    StreamThr :3756953 [internal.py:wandb_internal():85] W&B internal server running at pid: 3756953, started at: 2025-04-09 10:31:17.772883
2025-04-09 10:31:17,777 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status
2025-04-09 10:31:17,781 INFO    WriterThread:3756953 [datastore.py:open_for_write():87] open: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/run-46ff2xbo.wandb
2025-04-09 10:31:17,781 DEBUG   SenderThread:3756953 [sender.py:send():379] send: header
2025-04-09 10:31:17,789 DEBUG   SenderThread:3756953 [sender.py:send():379] send: run
2025-04-09 10:31:18,407 INFO    SenderThread:3756953 [dir_watcher.py:__init__():211] watching files in: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files
2025-04-09 10:31:18,407 INFO    SenderThread:3756953 [sender.py:_start_run_threads():1188] run started: 46ff2xbo with start time 1744183877.77232
2025-04-09 10:31:18,413 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: check_version
2025-04-09 10:31:18,414 DEBUG   SenderThread:3756953 [sender.py:send_request():406] send_request: check_version
2025-04-09 10:31:19,015 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: run_start
2025-04-09 10:31:19,025 DEBUG   HandlerThread:3756953 [system_info.py:__init__():26] System info init
2025-04-09 10:31:19,025 DEBUG   HandlerThread:3756953 [system_info.py:__init__():41] System info init done
2025-04-09 10:31:19,025 INFO    HandlerThread:3756953 [system_monitor.py:start():194] Starting system monitor
2025-04-09 10:31:19,026 INFO    SystemMonitor:3756953 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-09 10:31:19,026 INFO    HandlerThread:3756953 [system_monitor.py:probe():214] Collecting system info
2025-04-09 10:31:19,028 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started cpu monitoring
2025-04-09 10:31:19,029 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started disk monitoring
2025-04-09 10:31:19,030 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started gpu monitoring
2025-04-09 10:31:19,032 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started memory monitoring
2025-04-09 10:31:19,033 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started network monitoring
2025-04-09 10:31:19,055 DEBUG   HandlerThread:3756953 [system_info.py:probe():152] Probing system
2025-04-09 10:31:19,056 DEBUG   HandlerThread:3756953 [system_info.py:_probe_git():137] Probing git
2025-04-09 10:31:19,059 DEBUG   HandlerThread:3756953 [system_info.py:_probe_git():145] Probing git done
2025-04-09 10:31:19,059 DEBUG   HandlerThread:3756953 [system_info.py:probe():200] Probing system done
2025-04-09 10:31:19,059 DEBUG   HandlerThread:3756953 [system_monitor.py:probe():223] {'os': 'Linux-6.8.0-52-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2025-04-09T07:31:19.055216', 'startedAt': '2025-04-09T07:31:17.764936', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/arigra/Heavy-Clutter-Detection.git', 'commit': '18b10e19656126a5a79cdf5f12d96f04b43df4a7'}, 'email': 'ari.granevich@gmail.com', 'root': '/home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection', 'host': 'hawk-Z790-GAMING-X', 'username': 'hawk', 'executable': '/bin/python3', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1003.7446428571429, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1309.213, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1571.008, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1510.127, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1129.562, 'min': 800.0, 'max': 5600.0}, {'current': 1700.0, 'min': 800.0, 'max': 5600.0}, {'current': 1700.0, 'min': 800.0, 'max': 5600.0}, {'current': 1700.0, 'min': 800.0, 'max': 5600.0}, {'current': 1209.832, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1699.784, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1409.807, 'min': 800.0, 'max': 4300.0}, {'current': 1704.37, 'min': 800.0, 'max': 4300.0}, {'current': 1144.339, 'min': 800.0, 'max': 4300.0}, {'current': 1416.545, 'min': 800.0, 'max': 4300.0}, {'current': 1699.972, 'min': 800.0, 'max': 4300.0}, {'current': 1098.205, 'min': 800.0, 'max': 4300.0}, {'current': 1101.03, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1691.712, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 1832.2072448730469, 'used': 1105.826374053955}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.62469482421875}}
2025-04-09 10:31:19,059 INFO    HandlerThread:3756953 [system_monitor.py:probe():224] Finished collecting system info
2025-04-09 10:31:19,060 INFO    HandlerThread:3756953 [system_monitor.py:probe():227] Publishing system info
2025-04-09 10:31:19,060 INFO    HandlerThread:3756953 [system_monitor.py:probe():229] Finished publishing system info
2025-04-09 10:31:19,063 DEBUG   SenderThread:3756953 [sender.py:send():379] send: files
2025-04-09 10:31:19,063 INFO    SenderThread:3756953 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-04-09 10:31:19,172 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: python_packages
2025-04-09 10:31:19,173 DEBUG   SenderThread:3756953 [sender.py:send_request():406] send_request: python_packages
2025-04-09 10:31:19,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: stop_status
2025-04-09 10:31:19,173 DEBUG   SenderThread:3756953 [sender.py:send_request():406] send_request: stop_status
2025-04-09 10:31:19,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: pause
2025-04-09 10:31:19,174 INFO    HandlerThread:3756953 [handler.py:handle_request_pause():724] stopping system metrics thread
2025-04-09 10:31:19,174 INFO    HandlerThread:3756953 [system_monitor.py:finish():203] Stopping system monitor
2025-04-09 10:31:19,175 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-09 10:31:19,175 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-09 10:31:19,175 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined cpu monitor
2025-04-09 10:31:19,175 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-09 10:31:19,175 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined disk monitor
2025-04-09 10:31:19,226 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined gpu monitor
2025-04-09 10:31:19,226 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined memory monitor
2025-04-09 10:31:19,226 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined network monitor
2025-04-09 10:31:19,226 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:19,226 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: resume
2025-04-09 10:31:19,226 INFO    HandlerThread:3756953 [handler.py:handle_request_resume():715] starting system metrics thread
2025-04-09 10:31:19,226 INFO    HandlerThread:3756953 [system_monitor.py:start():194] Starting system monitor
2025-04-09 10:31:19,226 INFO    SystemMonitor:3756953 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-09 10:31:19,227 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started cpu monitoring
2025-04-09 10:31:19,227 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started disk monitoring
2025-04-09 10:31:19,227 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started gpu monitoring
2025-04-09 10:31:19,227 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started memory monitoring
2025-04-09 10:31:19,227 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started network monitoring
2025-04-09 10:31:19,408 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/wandb-metadata.json
2025-04-09 10:31:19,408 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/requirements.txt
2025-04-09 10:31:19,520 DEBUG   SenderThread:3756953 [sender.py:send():379] send: telemetry
2025-04-09 10:31:19,520 DEBUG   SenderThread:3756953 [sender.py:send():379] send: stats
2025-04-09 10:31:19,937 INFO    wandb-upload_0:3756953 [upload_job.py:push():130] Uploaded file /tmp/tmpjki16k1lwandb/nrtcwek6-wandb-metadata.json
2025-04-09 10:31:20,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:21,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:22,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:23,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:23,521 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status_report
2025-04-09 10:31:24,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:25,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:25,408 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:26,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:27,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:27,408 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:28,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:28,636 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status_report
2025-04-09 10:31:29,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:29,409 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:30,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:31,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:31,409 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:32,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:33,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:33,409 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:33,677 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status_report
2025-04-09 10:31:34,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: stop_status
2025-04-09 10:31:34,173 DEBUG   SenderThread:3756953 [sender.py:send_request():406] send_request: stop_status
2025-04-09 10:31:34,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:35,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:35,227 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:35,410 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:35,434 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: pause
2025-04-09 10:31:35,434 INFO    HandlerThread:3756953 [handler.py:handle_request_pause():724] stopping system metrics thread
2025-04-09 10:31:35,434 INFO    HandlerThread:3756953 [system_monitor.py:finish():203] Stopping system monitor
2025-04-09 10:31:35,435 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-09 10:31:35,435 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-09 10:31:35,435 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-09 10:31:35,435 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined cpu monitor
2025-04-09 10:31:35,435 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined disk monitor
2025-04-09 10:31:35,462 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined gpu monitor
2025-04-09 10:31:35,462 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined memory monitor
2025-04-09 10:31:35,462 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined network monitor
2025-04-09 10:31:35,463 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: resume
2025-04-09 10:31:35,463 INFO    HandlerThread:3756953 [handler.py:handle_request_resume():715] starting system metrics thread
2025-04-09 10:31:35,463 INFO    HandlerThread:3756953 [system_monitor.py:start():194] Starting system monitor
2025-04-09 10:31:35,463 INFO    SystemMonitor:3756953 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-09 10:31:35,463 DEBUG   SenderThread:3756953 [sender.py:send():379] send: stats
2025-04-09 10:31:35,463 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: pause
2025-04-09 10:31:35,463 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started cpu monitoring
2025-04-09 10:31:35,463 INFO    HandlerThread:3756953 [handler.py:handle_request_pause():724] stopping system metrics thread
2025-04-09 10:31:35,463 INFO    HandlerThread:3756953 [system_monitor.py:finish():203] Stopping system monitor
2025-04-09 10:31:35,464 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined cpu monitor
2025-04-09 10:31:35,464 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined disk monitor
2025-04-09 10:31:35,464 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started disk monitoring
2025-04-09 10:31:35,464 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-09 10:31:35,464 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-09 10:31:35,464 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-09 10:31:35,464 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: resume
2025-04-09 10:31:35,464 INFO    HandlerThread:3756953 [handler.py:handle_request_resume():715] starting system metrics thread
2025-04-09 10:31:35,464 INFO    HandlerThread:3756953 [system_monitor.py:start():194] Starting system monitor
2025-04-09 10:31:35,465 INFO    SystemMonitor:3756953 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-09 10:31:35,465 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started cpu monitoring
2025-04-09 10:31:35,465 DEBUG   SenderThread:3756953 [sender.py:send():379] send: stats
2025-04-09 10:31:35,465 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started disk monitoring
2025-04-09 10:31:35,465 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started gpu monitoring
2025-04-09 10:31:35,466 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started memory monitoring
2025-04-09 10:31:35,466 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started network monitoring
2025-04-09 10:31:35,895 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: pause
2025-04-09 10:31:35,895 INFO    HandlerThread:3756953 [handler.py:handle_request_pause():724] stopping system metrics thread
2025-04-09 10:31:35,895 INFO    HandlerThread:3756953 [system_monitor.py:finish():203] Stopping system monitor
2025-04-09 10:31:35,895 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined cpu monitor
2025-04-09 10:31:35,895 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined disk monitor
2025-04-09 10:31:35,895 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-09 10:31:35,895 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-09 10:31:35,895 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-09 10:31:35,926 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined gpu monitor
2025-04-09 10:31:35,926 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined memory monitor
2025-04-09 10:31:35,926 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined network monitor
2025-04-09 10:31:35,926 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: resume
2025-04-09 10:31:35,926 INFO    HandlerThread:3756953 [handler.py:handle_request_resume():715] starting system metrics thread
2025-04-09 10:31:35,926 INFO    HandlerThread:3756953 [system_monitor.py:start():194] Starting system monitor
2025-04-09 10:31:35,926 INFO    SystemMonitor:3756953 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-09 10:31:35,927 DEBUG   SenderThread:3756953 [sender.py:send():379] send: stats
2025-04-09 10:31:35,927 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started cpu monitoring
2025-04-09 10:31:35,927 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started disk monitoring
2025-04-09 10:31:35,928 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started gpu monitoring
2025-04-09 10:31:35,929 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started memory monitoring
2025-04-09 10:31:35,929 INFO    SystemMonitor:3756953 [interfaces.py:start():188] Started network monitoring
2025-04-09 10:31:36,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:37,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:37,248 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:37,410 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:38,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:39,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status_report
2025-04-09 10:31:39,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:39,260 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:39,411 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:40,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:41,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:41,308 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:41,411 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:42,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:43,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:43,237 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:43,411 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:44,174 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status_report
2025-04-09 10:31:44,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:45,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:45,302 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:45,412 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:46,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:47,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:47,239 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:47,412 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:48,175 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:49,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: stop_status
2025-04-09 10:31:49,173 DEBUG   SenderThread:3756953 [sender.py:send_request():406] send_request: stop_status
2025-04-09 10:31:49,213 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:49,295 ERROR   FileStreamThread:3756953 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/ari-granevich/Radar-diffusion/46ff2xbo/file_stream
NoneType: None
2025-04-09 10:31:49,412 INFO    Thread-12 :3756953 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/files/output.log
2025-04-09 10:31:49,429 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: status_report
2025-04-09 10:31:49,596 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:31:49,596 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:31:50,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:50,831 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:31:50,831 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:31:51,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:52,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:53,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:53,493 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:31:53,493 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:31:53,494 INFO    SenderThread:3756953 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hawk/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2025-04-09 10:31:54,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:55,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:56,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:57,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:57,794 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:31:57,794 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:31:58,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:31:58,740 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:31:59,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:00,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:01,176 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:02,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:03,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:04,173 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: stop_status
2025-04-09 10:32:04,213 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:05,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:06,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:07,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:07,624 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:32:07,624 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:32:08,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:09,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:10,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:11,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:12,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:13,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:14,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:15,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:16,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:17,177 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:18,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:19,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:20,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:21,016 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:32:21,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:22,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:23,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:24,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:25,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:26,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:27,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:27,490 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:32:27,490 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:32:28,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:29,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:30,178 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:31,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:32,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:33,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:34,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:35,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:35,929 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-09 10:32:36,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:37,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:38,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:39,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:40,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:41,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:42,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:43,179 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:43,302 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:32:44,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:45,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:46,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:47,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:48,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:49,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:50,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:51,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:52,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:53,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:54,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:55,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:56,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:57,180 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:58,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:32:59,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:00,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:01,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:02,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:03,121 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:33:03,121 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:33:03,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:04,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:05,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:05,609 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:33:06,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:07,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:08,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:09,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:10,181 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:11,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:12,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:13,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:14,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:15,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:16,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:17,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:18,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:19,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:20,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:21,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:22,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:23,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:24,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:25,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:26,182 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:27,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:28,019 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:33:28,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:29,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:30,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:31,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:32,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:33,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:34,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:35,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:36,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:37,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:38,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:39,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:40,183 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:41,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:42,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:43,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:44,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:45,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:46,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:47,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:48,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:49,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:50,184 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:50,482 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:33:51,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:52,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:53,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:54,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:55,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:56,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:57,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:58,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:33:59,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:00,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:01,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:02,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:03,185 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:04,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:05,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:06,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:07,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:08,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:09,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:10,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:11,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:12,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:12,935 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: partial_history
2025-04-09 10:34:13,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:14,186 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:15,187 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:16,187 DEBUG   HandlerThread:3756953 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-09 10:34:16,235 ERROR   SenderThread:3756953 [internal_api.py:execute():344] 409 response executing GraphQL.
2025-04-09 10:34:16,235 ERROR   SenderThread:3756953 [internal_api.py:execute():345] {"errors":[{"message":"run 46ff2xbo was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-04-09 10:34:16,236 INFO    HandlerThread:3756953 [handler.py:finish():882] shutting down handler
2025-04-09 10:34:16,236 INFO    HandlerThread:3756953 [system_monitor.py:finish():203] Stopping system monitor
2025-04-09 10:34:16,236 INFO    WriterThread:3756953 [datastore.py:close():296] close: /home/hawk/Desktop/Heavy Detector/Heavy-Clutter-Detection/finalDiffusion/wandb/run-20250409_103117-46ff2xbo/run-46ff2xbo.wandb
2025-04-09 10:34:16,236 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-09 10:34:16,236 DEBUG   SystemMonitor:3756953 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-09 10:34:16,236 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined cpu monitor
2025-04-09 10:34:16,237 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined disk monitor
2025-04-09 10:34:16,283 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined gpu monitor
2025-04-09 10:34:16,284 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined memory monitor
2025-04-09 10:34:16,284 INFO    HandlerThread:3756953 [interfaces.py:finish():200] Joined network monitor
2025-04-09 10:34:16,951 ERROR   StreamThr :3756953 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2188, in upsert_run
    response = self.gql(
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hawk/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 92, in _run
    self._debounce()
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 333, in _debounce
    self._sm.debounce()
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 537, in debounce
    self._maybe_update_config(always=final)
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 514, in _maybe_update_config
    self._debounce_config()
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 543, in _debounce_config
    self._api.upsert_run(
  File "/home/hawk/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run 46ff2xbo was previously created and deleted; try a new run name (Error 409: Conflict)
